spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: role-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: "jdbc:postgresql://0.0.0.0:5432/orders_db"
    username: postgres
    password: 123
    changelog-file:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update