version: '3'

services:
#  order-manager:
#    build: order-manager
#    ports:
#      - 8080:8080
#    environment:
#      - POSTGRES_DB=orders_db
#    networks:
#      - postgres-compose-network
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge